name: weatherapp
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  lottie: ^3.1.0
  flutter_spinkit: ^5.2.1
  smooth_page_indicator: ^1.1.0
  dio: ^5.4.3
  location: ^6.0.2
  permission_handler: ^11.3.1
  geolocator: ^11.0.0
  intl: ^0.19.0
  pull_to_refresh_flutter3: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  image_path: "assets/icon/OIG1.jfif"
  


flutter:
  uses-material-design: true
  assets:
   - assets/json/
   - assets/icon/
   - assets/gif/
  #  - images/a_dot_ham.jpeg
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
